### ISSUE TITLE
I have a few doubts i would like to clarify, is there any other way that i can communicate with you?

### ISSUE THREAD

**Issue by tariqaq** [BennyOe/arch_install#1]

**Comment by BennyOe** [comment]
sure. I sent you a mail to your gmail. ;)

**Comment by tariqaq** [comment]
Hi there,
Regarding your uefi dualboot mode for the script--

I have a laptop that has windows installed on an nvme ssd, with uefi.
Usually i dont see a recovery partition on any of my windows pc, but on my
main one, i recently formatted and reinstalled windows 10, and this time i
see recovery partition as also been made.
[image: image.png]
So will this affect your script for dualboot?

**Comment by BennyOe** [comment]
Hi,
no, it shouldn't. When I installed arch on my surface there was also a recovery partition visible and the script installed successfully.

**Comment by tariqaq** [comment]
Great, thanks!
